(cl:defpackage articulated_control-msg
  (:use )
  (:export
   "<ARTICULATEDSTATE>"
   "ARTICULATEDSTATE"
   "<CONTROLSEQUENCEVW>"
   "CONTROLSEQUENCEVW"
   "<FLEETEXPECTEDSEQUENCE>"
   "FLEETEXPECTEDSEQUENCE"
   "<FLEETPHI>"
   "FLEETPHI"
   "<FLEETSTATE>"
   "FLEETSTATE"
   "<VEHICLESTATE>"
   "VEHICLESTATE"
  ))

