// Generated by gencpp from file articulated_control/ArticulatedState.msg
// DO NOT EDIT!


#ifndef ARTICULATED_CONTROL_MESSAGE_ARTICULATEDSTATE_H
#define ARTICULATED_CONTROL_MESSAGE_ARTICULATEDSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <articulated_control/VehicleState.h>

namespace articulated_control
{
template <class ContainerAllocator>
struct ArticulatedState_
{
  typedef ArticulatedState_<ContainerAllocator> Type;

  ArticulatedState_()
    : header()
    , vehicles()
    , thetas()  {
    }
  ArticulatedState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vehicles(_alloc)
    , thetas(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::articulated_control::VehicleState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::articulated_control::VehicleState_<ContainerAllocator> >> _vehicles_type;
  _vehicles_type vehicles;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _thetas_type;
  _thetas_type thetas;





  typedef boost::shared_ptr< ::articulated_control::ArticulatedState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::articulated_control::ArticulatedState_<ContainerAllocator> const> ConstPtr;

}; // struct ArticulatedState_

typedef ::articulated_control::ArticulatedState_<std::allocator<void> > ArticulatedState;

typedef boost::shared_ptr< ::articulated_control::ArticulatedState > ArticulatedStatePtr;
typedef boost::shared_ptr< ::articulated_control::ArticulatedState const> ArticulatedStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::articulated_control::ArticulatedState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::articulated_control::ArticulatedState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::articulated_control::ArticulatedState_<ContainerAllocator1> & lhs, const ::articulated_control::ArticulatedState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.vehicles == rhs.vehicles &&
    lhs.thetas == rhs.thetas;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::articulated_control::ArticulatedState_<ContainerAllocator1> & lhs, const ::articulated_control::ArticulatedState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace articulated_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::articulated_control::ArticulatedState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::articulated_control::ArticulatedState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::articulated_control::ArticulatedState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::articulated_control::ArticulatedState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::articulated_control::ArticulatedState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::articulated_control::ArticulatedState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::articulated_control::ArticulatedState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cfbc1c7809bcb64528484d5d27e5c607";
  }

  static const char* value(const ::articulated_control::ArticulatedState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcfbc1c7809bcb645ULL;
  static const uint64_t static_value2 = 0x28484d5d27e5c607ULL;
};

template<class ContainerAllocator>
struct DataType< ::articulated_control::ArticulatedState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "articulated_control/ArticulatedState";
  }

  static const char* value(const ::articulated_control::ArticulatedState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::articulated_control::ArticulatedState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"VehicleState[] vehicles\n"
"float64[] thetas\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: articulated_control/VehicleState\n"
"float64 x\n"
"float64 y\n"
"float64 phi\n"
"float64 L\n"
;
  }

  static const char* value(const ::articulated_control::ArticulatedState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::articulated_control::ArticulatedState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vehicles);
      stream.next(m.thetas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArticulatedState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::articulated_control::ArticulatedState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::articulated_control::ArticulatedState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vehicles[]" << std::endl;
    for (size_t i = 0; i < v.vehicles.size(); ++i)
    {
      s << indent << "  vehicles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::articulated_control::VehicleState_<ContainerAllocator> >::stream(s, indent + "    ", v.vehicles[i]);
    }
    s << indent << "thetas[]" << std::endl;
    for (size_t i = 0; i < v.thetas.size(); ++i)
    {
      s << indent << "  thetas[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.thetas[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARTICULATED_CONTROL_MESSAGE_ARTICULATEDSTATE_H
