// Generated by gencpp from file articulated_control/ControlSequenceVW.msg
// DO NOT EDIT!


#ifndef ARTICULATED_CONTROL_MESSAGE_CONTROLSEQUENCEVW_H
#define ARTICULATED_CONTROL_MESSAGE_CONTROLSEQUENCEVW_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace articulated_control
{
template <class ContainerAllocator>
struct ControlSequenceVW_
{
  typedef ControlSequenceVW_<ContainerAllocator> Type;

  ControlSequenceVW_()
    : v_sequence()
    , w_sequence()  {
    }
  ControlSequenceVW_(const ContainerAllocator& _alloc)
    : v_sequence(_alloc)
    , w_sequence(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _v_sequence_type;
  _v_sequence_type v_sequence;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _w_sequence_type;
  _w_sequence_type w_sequence;





  typedef boost::shared_ptr< ::articulated_control::ControlSequenceVW_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::articulated_control::ControlSequenceVW_<ContainerAllocator> const> ConstPtr;

}; // struct ControlSequenceVW_

typedef ::articulated_control::ControlSequenceVW_<std::allocator<void> > ControlSequenceVW;

typedef boost::shared_ptr< ::articulated_control::ControlSequenceVW > ControlSequenceVWPtr;
typedef boost::shared_ptr< ::articulated_control::ControlSequenceVW const> ControlSequenceVWConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::articulated_control::ControlSequenceVW_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::articulated_control::ControlSequenceVW_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::articulated_control::ControlSequenceVW_<ContainerAllocator1> & lhs, const ::articulated_control::ControlSequenceVW_<ContainerAllocator2> & rhs)
{
  return lhs.v_sequence == rhs.v_sequence &&
    lhs.w_sequence == rhs.w_sequence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::articulated_control::ControlSequenceVW_<ContainerAllocator1> & lhs, const ::articulated_control::ControlSequenceVW_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace articulated_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::articulated_control::ControlSequenceVW_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::articulated_control::ControlSequenceVW_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::articulated_control::ControlSequenceVW_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::articulated_control::ControlSequenceVW_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::articulated_control::ControlSequenceVW_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::articulated_control::ControlSequenceVW_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::articulated_control::ControlSequenceVW_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27d78ee3dbd06ca542a270fa283a2711";
  }

  static const char* value(const ::articulated_control::ControlSequenceVW_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27d78ee3dbd06ca5ULL;
  static const uint64_t static_value2 = 0x42a270fa283a2711ULL;
};

template<class ContainerAllocator>
struct DataType< ::articulated_control::ControlSequenceVW_<ContainerAllocator> >
{
  static const char* value()
  {
    return "articulated_control/ControlSequenceVW";
  }

  static const char* value(const ::articulated_control::ControlSequenceVW_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::articulated_control::ControlSequenceVW_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Flattened per-vehicle control sequences (time-major):\n"
"# index = t * n_vehicles + i\n"
"float64[] v_sequence\n"
"float64[] w_sequence\n"
;
  }

  static const char* value(const ::articulated_control::ControlSequenceVW_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::articulated_control::ControlSequenceVW_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v_sequence);
      stream.next(m.w_sequence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlSequenceVW_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::articulated_control::ControlSequenceVW_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::articulated_control::ControlSequenceVW_<ContainerAllocator>& v)
  {
    s << indent << "v_sequence[]" << std::endl;
    for (size_t i = 0; i < v.v_sequence.size(); ++i)
    {
      s << indent << "  v_sequence[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.v_sequence[i]);
    }
    s << indent << "w_sequence[]" << std::endl;
    for (size_t i = 0; i < v.w_sequence.size(); ++i)
    {
      s << indent << "  w_sequence[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.w_sequence[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARTICULATED_CONTROL_MESSAGE_CONTROLSEQUENCEVW_H
