// Generated by gencpp from file articulated_control/FleetState.msg
// DO NOT EDIT!


#ifndef ARTICULATED_CONTROL_MESSAGE_FLEETSTATE_H
#define ARTICULATED_CONTROL_MESSAGE_FLEETSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace articulated_control
{
template <class ContainerAllocator>
struct FleetState_
{
  typedef FleetState_<ContainerAllocator> Type;

  FleetState_()
    : header()
    , n_vehicles(0)
    , phis()
    , thetas()  {
    }
  FleetState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , n_vehicles(0)
    , phis(_alloc)
    , thetas(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _n_vehicles_type;
  _n_vehicles_type n_vehicles;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _phis_type;
  _phis_type phis;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _thetas_type;
  _thetas_type thetas;





  typedef boost::shared_ptr< ::articulated_control::FleetState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::articulated_control::FleetState_<ContainerAllocator> const> ConstPtr;

}; // struct FleetState_

typedef ::articulated_control::FleetState_<std::allocator<void> > FleetState;

typedef boost::shared_ptr< ::articulated_control::FleetState > FleetStatePtr;
typedef boost::shared_ptr< ::articulated_control::FleetState const> FleetStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::articulated_control::FleetState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::articulated_control::FleetState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::articulated_control::FleetState_<ContainerAllocator1> & lhs, const ::articulated_control::FleetState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.n_vehicles == rhs.n_vehicles &&
    lhs.phis == rhs.phis &&
    lhs.thetas == rhs.thetas;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::articulated_control::FleetState_<ContainerAllocator1> & lhs, const ::articulated_control::FleetState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace articulated_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::articulated_control::FleetState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::articulated_control::FleetState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::articulated_control::FleetState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::articulated_control::FleetState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::articulated_control::FleetState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::articulated_control::FleetState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::articulated_control::FleetState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45f54608f7b08a0f1eb43e850318378f";
  }

  static const char* value(const ::articulated_control::FleetState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45f54608f7b08a0fULL;
  static const uint64_t static_value2 = 0x1eb43e850318378fULL;
};

template<class ContainerAllocator>
struct DataType< ::articulated_control::FleetState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "articulated_control/FleetState";
  }

  static const char* value(const ::articulated_control::FleetState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::articulated_control::FleetState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 n_vehicles\n"
"float64[] phis\n"
"float64[] thetas\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::articulated_control::FleetState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::articulated_control::FleetState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.n_vehicles);
      stream.next(m.phis);
      stream.next(m.thetas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FleetState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::articulated_control::FleetState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::articulated_control::FleetState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "n_vehicles: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n_vehicles);
    s << indent << "phis[]" << std::endl;
    for (size_t i = 0; i < v.phis.size(); ++i)
    {
      s << indent << "  phis[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.phis[i]);
    }
    s << indent << "thetas[]" << std::endl;
    for (size_t i = 0; i < v.thetas.size(); ++i)
    {
      s << indent << "  thetas[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.thetas[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARTICULATED_CONTROL_MESSAGE_FLEETSTATE_H
