// Generated by gencpp from file articulated_control/FleetPhi.msg
// DO NOT EDIT!


#ifndef ARTICULATED_CONTROL_MESSAGE_FLEETPHI_H
#define ARTICULATED_CONTROL_MESSAGE_FLEETPHI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace articulated_control
{
template <class ContainerAllocator>
struct FleetPhi_
{
  typedef FleetPhi_<ContainerAllocator> Type;

  FleetPhi_()
    : header()
    , n_vehicles(0)
    , phis()
    , timestamps_ms()  {
    }
  FleetPhi_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , n_vehicles(0)
    , phis(_alloc)
    , timestamps_ms(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _n_vehicles_type;
  _n_vehicles_type n_vehicles;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _phis_type;
  _phis_type phis;

   typedef std::vector<uint64_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint64_t>> _timestamps_ms_type;
  _timestamps_ms_type timestamps_ms;





  typedef boost::shared_ptr< ::articulated_control::FleetPhi_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::articulated_control::FleetPhi_<ContainerAllocator> const> ConstPtr;

}; // struct FleetPhi_

typedef ::articulated_control::FleetPhi_<std::allocator<void> > FleetPhi;

typedef boost::shared_ptr< ::articulated_control::FleetPhi > FleetPhiPtr;
typedef boost::shared_ptr< ::articulated_control::FleetPhi const> FleetPhiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::articulated_control::FleetPhi_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::articulated_control::FleetPhi_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::articulated_control::FleetPhi_<ContainerAllocator1> & lhs, const ::articulated_control::FleetPhi_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.n_vehicles == rhs.n_vehicles &&
    lhs.phis == rhs.phis &&
    lhs.timestamps_ms == rhs.timestamps_ms;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::articulated_control::FleetPhi_<ContainerAllocator1> & lhs, const ::articulated_control::FleetPhi_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace articulated_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::articulated_control::FleetPhi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::articulated_control::FleetPhi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::articulated_control::FleetPhi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::articulated_control::FleetPhi_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::articulated_control::FleetPhi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::articulated_control::FleetPhi_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::articulated_control::FleetPhi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "912f038e1cf337e5ff7786fe07ace650";
  }

  static const char* value(const ::articulated_control::FleetPhi_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x912f038e1cf337e5ULL;
  static const uint64_t static_value2 = 0xff7786fe07ace650ULL;
};

template<class ContainerAllocator>
struct DataType< ::articulated_control::FleetPhi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "articulated_control/FleetPhi";
  }

  static const char* value(const ::articulated_control::FleetPhi_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::articulated_control::FleetPhi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 n_vehicles\n"
"float64[] phis\n"
"uint64[] timestamps_ms\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::articulated_control::FleetPhi_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::articulated_control::FleetPhi_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.n_vehicles);
      stream.next(m.phis);
      stream.next(m.timestamps_ms);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FleetPhi_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::articulated_control::FleetPhi_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::articulated_control::FleetPhi_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "n_vehicles: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n_vehicles);
    s << indent << "phis[]" << std::endl;
    for (size_t i = 0; i < v.phis.size(); ++i)
    {
      s << indent << "  phis[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.phis[i]);
    }
    s << indent << "timestamps_ms[]" << std::endl;
    for (size_t i = 0; i < v.timestamps_ms.size(); ++i)
    {
      s << indent << "  timestamps_ms[" << i << "]: ";
      Printer<uint64_t>::stream(s, indent + "  ", v.timestamps_ms[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARTICULATED_CONTROL_MESSAGE_FLEETPHI_H
