// Generated by gencpp from file articulated_control/FleetExpectedSequence.msg
// DO NOT EDIT!


#ifndef ARTICULATED_CONTROL_MESSAGE_FLEETEXPECTEDSEQUENCE_H
#define ARTICULATED_CONTROL_MESSAGE_FLEETEXPECTEDSEQUENCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace articulated_control
{
template <class ContainerAllocator>
struct FleetExpectedSequence_
{
  typedef FleetExpectedSequence_<ContainerAllocator> Type;

  FleetExpectedSequence_()
    : header()
    , n_vehicles(0)
    , horizon(0)
    , leg_length(0.0)
    , v_sequence()
    , w_sequence()
    , phi_sequence()
    , theta_sequence()  {
    }
  FleetExpectedSequence_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , n_vehicles(0)
    , horizon(0)
    , leg_length(0.0)
    , v_sequence(_alloc)
    , w_sequence(_alloc)
    , phi_sequence(_alloc)
    , theta_sequence(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _n_vehicles_type;
  _n_vehicles_type n_vehicles;

   typedef int32_t _horizon_type;
  _horizon_type horizon;

   typedef double _leg_length_type;
  _leg_length_type leg_length;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _v_sequence_type;
  _v_sequence_type v_sequence;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _w_sequence_type;
  _w_sequence_type w_sequence;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _phi_sequence_type;
  _phi_sequence_type phi_sequence;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _theta_sequence_type;
  _theta_sequence_type theta_sequence;





  typedef boost::shared_ptr< ::articulated_control::FleetExpectedSequence_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::articulated_control::FleetExpectedSequence_<ContainerAllocator> const> ConstPtr;

}; // struct FleetExpectedSequence_

typedef ::articulated_control::FleetExpectedSequence_<std::allocator<void> > FleetExpectedSequence;

typedef boost::shared_ptr< ::articulated_control::FleetExpectedSequence > FleetExpectedSequencePtr;
typedef boost::shared_ptr< ::articulated_control::FleetExpectedSequence const> FleetExpectedSequenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::articulated_control::FleetExpectedSequence_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::articulated_control::FleetExpectedSequence_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::articulated_control::FleetExpectedSequence_<ContainerAllocator1> & lhs, const ::articulated_control::FleetExpectedSequence_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.n_vehicles == rhs.n_vehicles &&
    lhs.horizon == rhs.horizon &&
    lhs.leg_length == rhs.leg_length &&
    lhs.v_sequence == rhs.v_sequence &&
    lhs.w_sequence == rhs.w_sequence &&
    lhs.phi_sequence == rhs.phi_sequence &&
    lhs.theta_sequence == rhs.theta_sequence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::articulated_control::FleetExpectedSequence_<ContainerAllocator1> & lhs, const ::articulated_control::FleetExpectedSequence_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace articulated_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::articulated_control::FleetExpectedSequence_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::articulated_control::FleetExpectedSequence_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::articulated_control::FleetExpectedSequence_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::articulated_control::FleetExpectedSequence_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::articulated_control::FleetExpectedSequence_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::articulated_control::FleetExpectedSequence_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::articulated_control::FleetExpectedSequence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0beb448df9f9c2436a4d59ffca7378f5";
  }

  static const char* value(const ::articulated_control::FleetExpectedSequence_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0beb448df9f9c243ULL;
  static const uint64_t static_value2 = 0x6a4d59ffca7378f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::articulated_control::FleetExpectedSequence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "articulated_control/FleetExpectedSequence";
  }

  static const char* value(const ::articulated_control::FleetExpectedSequence_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::articulated_control::FleetExpectedSequence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 n_vehicles\n"
"int32 horizon\n"
"float64 leg_length\n"
"float64[] v_sequence\n"
"float64[] w_sequence\n"
"float64[] phi_sequence\n"
"float64[] theta_sequence\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::articulated_control::FleetExpectedSequence_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::articulated_control::FleetExpectedSequence_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.n_vehicles);
      stream.next(m.horizon);
      stream.next(m.leg_length);
      stream.next(m.v_sequence);
      stream.next(m.w_sequence);
      stream.next(m.phi_sequence);
      stream.next(m.theta_sequence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FleetExpectedSequence_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::articulated_control::FleetExpectedSequence_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::articulated_control::FleetExpectedSequence_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "n_vehicles: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n_vehicles);
    s << indent << "horizon: ";
    Printer<int32_t>::stream(s, indent + "  ", v.horizon);
    s << indent << "leg_length: ";
    Printer<double>::stream(s, indent + "  ", v.leg_length);
    s << indent << "v_sequence[]" << std::endl;
    for (size_t i = 0; i < v.v_sequence.size(); ++i)
    {
      s << indent << "  v_sequence[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.v_sequence[i]);
    }
    s << indent << "w_sequence[]" << std::endl;
    for (size_t i = 0; i < v.w_sequence.size(); ++i)
    {
      s << indent << "  w_sequence[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.w_sequence[i]);
    }
    s << indent << "phi_sequence[]" << std::endl;
    for (size_t i = 0; i < v.phi_sequence.size(); ++i)
    {
      s << indent << "  phi_sequence[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.phi_sequence[i]);
    }
    s << indent << "theta_sequence[]" << std::endl;
    for (size_t i = 0; i < v.theta_sequence.size(); ++i)
    {
      s << indent << "  theta_sequence[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.theta_sequence[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARTICULATED_CONTROL_MESSAGE_FLEETEXPECTEDSEQUENCE_H
