// Generated by gencpp from file articulated_control/VehicleState.msg
// DO NOT EDIT!


#ifndef ARTICULATED_CONTROL_MESSAGE_VEHICLESTATE_H
#define ARTICULATED_CONTROL_MESSAGE_VEHICLESTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace articulated_control
{
template <class ContainerAllocator>
struct VehicleState_
{
  typedef VehicleState_<ContainerAllocator> Type;

  VehicleState_()
    : x(0.0)
    , y(0.0)
    , phi(0.0)
    , L(0.0)  {
    }
  VehicleState_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , phi(0.0)
    , L(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _phi_type;
  _phi_type phi;

   typedef double _L_type;
  _L_type L;





  typedef boost::shared_ptr< ::articulated_control::VehicleState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::articulated_control::VehicleState_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleState_

typedef ::articulated_control::VehicleState_<std::allocator<void> > VehicleState;

typedef boost::shared_ptr< ::articulated_control::VehicleState > VehicleStatePtr;
typedef boost::shared_ptr< ::articulated_control::VehicleState const> VehicleStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::articulated_control::VehicleState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::articulated_control::VehicleState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::articulated_control::VehicleState_<ContainerAllocator1> & lhs, const ::articulated_control::VehicleState_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.phi == rhs.phi &&
    lhs.L == rhs.L;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::articulated_control::VehicleState_<ContainerAllocator1> & lhs, const ::articulated_control::VehicleState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace articulated_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::articulated_control::VehicleState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::articulated_control::VehicleState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::articulated_control::VehicleState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::articulated_control::VehicleState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::articulated_control::VehicleState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::articulated_control::VehicleState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::articulated_control::VehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec55d4b4fb9a73db2de8096f64140e9a";
  }

  static const char* value(const ::articulated_control::VehicleState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec55d4b4fb9a73dbULL;
  static const uint64_t static_value2 = 0x2de8096f64140e9aULL;
};

template<class ContainerAllocator>
struct DataType< ::articulated_control::VehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "articulated_control/VehicleState";
  }

  static const char* value(const ::articulated_control::VehicleState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::articulated_control::VehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 phi\n"
"float64 L\n"
;
  }

  static const char* value(const ::articulated_control::VehicleState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::articulated_control::VehicleState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.phi);
      stream.next(m.L);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::articulated_control::VehicleState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::articulated_control::VehicleState_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "phi: ";
    Printer<double>::stream(s, indent + "  ", v.phi);
    s << indent << "L: ";
    Printer<double>::stream(s, indent + "  ", v.L);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARTICULATED_CONTROL_MESSAGE_VEHICLESTATE_H
